name: oman_service
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true